Fix poms, modernize
jenkinsci/js-libs pull request #25
Opened 2023-01-25 11:38 UTC by daniel-beck

## Motivation

The plugins in this repository stand out as being by far the least actively maintained among the top 100 plugins by popularity.

They're by far the least recently released (March 2016) and have by far the oldest core dependency (1.580.1). Since `ace-editor` is a dependency of `workflow-cps`, there's no modern Pipeline-based Jenkins possible without it, making removal of unused implied dependencies cumbersome to impossible.

## PR Content

This fixes the pom references broken since https://github.com/jenkinsci/js-libs/commit/2048280a7b9bb56ac33c7d170be7d891a7cbaaec, and updates to the newest plugin parent POM.

As a result, this now depends on Jenkins 2.361 and requires Java 11 to build.

Also documented the `core.symlinks` requirement for Git.

2023-01-25 13:04 UTC, alecharp approved these changes
Works well locally

2023-01-30 23:21 UTC, MarkEWaite approved these changes
Yes, many times yes.  Modernizing `ace-editor` will avoid future pain if jdk-tool or one of the older split plugins is deprecated.  The deprecation of `windows-slaves` highlighted the type of problems that users can see due to implied dependencies.

2023-02-01 00:55 UTC, basil requested changes
https://github.com/jenkinsci/workflow-cps-plugin/pull/653 is likely more maintainable.

2023-02-01 10:18 UTC, daniel-beck commented
@basil This is great, thank you.

2023-02-01 10:18 UTC, closed without merging